[focus-ios] Issue2308 - l10n ci implementation into refresh (https://github.com/mozilla-mobile/focus-ios/issues/2309)
* Get Screenshots on CI: Enable Taskcluster and Taskgraph - Part 2 (https://github.com/mozilla-mobile/focus-ios/issues/1978)

* l10nScreenshots Enable Taskcluster and Taskgraph

* remove project and install-sdk and use mobile.v2.focus-ios

* comment to use bitrise workers and modifications according to latest files

Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>

* fix shipping locales conflict

* L10n part4 and part 8 add all scripts needed (https://github.com/mozilla-mobile/focus-ios/pull/2029)

* Part 4 - Get screenshots on CI

* changes to get part 4 and 8 implemented

* remove  reference

* remove Klar references for now

* L10n follow up missing docker file (https://github.com/mozilla-mobile/focus-ios/issues/2047)

* l10n follow up add missing docker directory

* remove unnecesary file

* l10n follow up 2 missing ci/build directory (https://github.com/mozilla-mobile/focus-ios/pull/2049)

* l10n follow up 2 missing ci/build directory

* modify config.yml

* l10n follow up 3 fix naming error in taskcluster.yml

* l10n-follow-up-4-update-L10nBuild-workflow

* l10n-follow-up-5-missing-arguments-init

* l10n-follow-up-6-wait-for-bitrise-api-response (https://github.com/mozilla-mobile/focus-ios/pull/2111)

* l10n-follow-up-6-wait-for-bitrise-api-response

* better with asyncio

* l10n-follow-up-7-bitrise-workaround-for-fastlane-issue

* l10n-follow-up-8-fix-download-derived-data-path (https://github.com/mozilla-mobile/focus-ios/issues/2124)

* l10n-follow-up-8-fix-download-derived-data-path

* print error

* setting default workflow back

* l10n-follow-up-9-do-not-compress-artifacts-folder (https://github.com/mozilla-mobile/focus-ios/issues/2126)

* l10n-follow-up-9-do-not-compress-artifacts-folder

* undo changes for testing

* undo changes for testing default workflow

Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>

diff --git a/focus-ios/bitrise.yml b/focus-ios/bitrise.yml
--- a/focus-ios/bitrise.yml
+++ b/focus-ios/bitrise.yml
@@ -313,6 +313,71 @@ workflows:
         stack: osx-xcode-12.5.x
         machine_type_id: g2.8core
 
+  L10nScreenshotsTests:
+    steps:
+    - activate-ssh-key@4:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone@4: {}
+    - cache-pull@2: {}
+    - certificate-and-profile-installer@1: {}
+    - script@1:
+        title: Set Default Web Browser Entitlement
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -x
+            /usr/libexec/PlistBuddy -c "Add :com.apple.developer.web-browser bool true" Focus.entitlements
+            /usr/libexec/PlistBuddy -c "Add :com.apple.developer.web-browser bool true" Klar.entitlements
+    - script@1:
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+
+            # fail if any commands fails
+
+            set -e
+
+            # debug log
+
+            set -x
+
+            echo "curl to Download derived data"
+
+            curl --location --retry 5 --output l10n-screenshots-dd.zip "$MOZ_DERIVED_DATA_PATH"
+
+            mkdir l10n-screenshots-dd
+
+            unzip l10n-screenshots-dd.zip -d l10n-screenshots-dd
+
+            rm l10n-screenshots-dd.zip
+        title: Download derived data path
+    - script@1:
+        title: Generate screenshots
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+            # workaround until 2.187 version is installed. Error with 2.186
+            fastlane update_fastlane
+
+            ./l10n-screenshots.sh --test-without-building $MOZ_LOCALES
+            mkdir -p artifacts
+
+            for locale in $(echo $MOZ_LOCALES); do
+              # Only Focus for now
+              zip -9 -j "$locale.zip" "l10n-screenshots/$locale/$locale/"*
+              mv "$locale.zip" artifacts/
+            done
+    - deploy-to-bitrise-io@1.10:
+        inputs:
+        - deploy_path: artifacts/
+    meta:
+      bitrise.io:
+        stack: osx-xcode-12.5.x
+        machine_type_id: standard
   L10nBuild:
     steps:
     - activate-ssh-key@4:
@@ -340,20 +405,21 @@ workflows:
         - content: |-
             #!/usr/bin/env bash
             set -x
-            ./screenshots.sh en-US
-
+            # workaround until 2.187 version is installed. Error with 2.186
+            fastlane update_fastlane
+            ./l10n-screenshots.sh en-US
     - deploy-to-bitrise-io@1.10:
         inputs:
-        - deploy_path: screenshots-derived-data/
+        - deploy_path: l10n-screenshots-dd/
         - is_compress: 'true'
     - deploy-to-bitrise-io@1.10:
         inputs:
-        - deploy_path: screenshots/Focus/iPhone11/en-US
+        - deploy_path: l10n-screenshots/en-US/en-US
         - is_compress: 'true'
     meta:
       bitrise.io:
         stack: osx-xcode-12.5.x
-        machine_type_id: standard
+        machine_type_id: g2.4core
 
 app:
   envs:
