Moved glean script out of ApplicationServices framework v69.0.0 to source directory (#8021)
- Updated bitrise.yml and bootstrap to fix Application Services v69.0.0 changes
- Moved glean script out of ApplicationServices framework v69.0.0 to Firefox source directory. We don't want this script to be signed
- MozillaAppServices copy framework will now be handled by Carthage

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1073,10 +1073,25 @@ workflows:
             # debug log
             set -x
 
-
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
         title: remove carthage lipo workaround
+    - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
     - script@1:
         inputs:
         - content: >-
@@ -1491,6 +1506,22 @@ workflows:
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
         title: remove carthage lipo workaround
+    - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
     - script@1:
         inputs:
         - content: >-
