create testing workflow

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -597,6 +597,56 @@ workflows:
     - RunSmokeXCUITests
     - Detect_warnings
     - 5_deploy_and_slack
+  
+  RunUnitTestsM1Beta:
+    # Temporary workflow created for testing purposes
+    steps:
+    - script@1.1:
+        title: Detect number of warnings
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            TEST_LOG_PATH=$BITRISE_XCODEBUILD_TEST_LOG_PATH
+
+            COUNT=$(./test-fixtures/generate-metrics.sh $TEST_LOG_PATH unit-test)
+            envman add --key SHOW_WARNING_COUNT --value "$COUNT"
+            envman add --key SHOW_WARNING_IN_SLACK --value Show_Warnings
+
+            STR=$COUNT
+            SUB='greater'
+            if [[ "$STR" == *"$SUB"* ]]; then
+                echo "Failure, the number of warnings increased"
+                exit 1
+            fi
+        is_always_run: true
+    - slack@3.1:
+        run_if: '{{getenv "NEW_AS_VERSION" | eq "New_AS_Version"}}'
+        inputs:
+        - channel: "#firefox-ios"
+        - text: Build status using latest A-S
+        - webhook_url: $WEBHOOK_SLACK_TOKEN_2
+    description: >-
+      This Workflow is to run tests (currently SmokeTest) when there is a merge
+      in master
+    meta:
+      bitrise.io:
+        stack: osx-xcode-13.1.x
+        # To be changed to the proper M1 MacMini when available
+        machine_type_id: g2.4core
+    before_run:
+    - 1_git_clone_and_post_clone
+    - 2_certificate_and_profile
+    - 3_provisioning_and_npm_installation
+    - 4_A_xcode_build_and_test_Fennec
+    after_run:
+    - RunSmokeXCUITests
+    - Detect_warnings
+    - 5_deploy_and_slack
   RunSmokeXCUITests:
     steps:
     - cache-pull@2.1:
