add danger after unit tests

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -60,6 +60,16 @@ workflows:
         - xcodebuild_options: '"-derivedDataPath DerivedData" "COMPILER_INDEX_STORE_ENABLE=NO"
             "CODE_SIGN_IDENTITY=" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGNING_ALLOWED=NO"'
     - script@1.1:
+        title: Run Danger
+        is_always_run: true
+        inputs:
+        - content: |
+            #!/usr/bin/env bash
+            # Fail if any command fails
+            set -e
+            echo "Run danger"
+            swift run danger-swift ci
+    - script@1.1:
         title: Detect number of warnings
         is_always_run: true
         inputs:
