Refactor FXIOS-12055 #26253 ⁃ Add logic to Danger to fail PR that add files without test (#26254)
---------

Co-authored-by: isabelrios <isabelrios@gmail.com>

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -191,8 +191,24 @@ workflows:
             #!/usr/bin/env bash
             # Fail if any command fails
             set -e
-            echo "Run danger"
+            # Extract .xcresult using xcrun xccov
+            echo "Generating coverage.json from xcresult..."
+            xcrun xccov view --report --json "$BITRISE_XCRESULT_PATH" > coverage.json
+            echo "coverage.json created successfully"
+
+            # Define a cleanup function to remove the file
+            function cleanup_coverage {
+              if [ -f coverage.json ]; then
+                echo "Removing coverage.json"
+                rm coverage.json
+              fi
+            }
+            # Register it to run on script exit
+            trap cleanup_coverage EXIT
+
+            echo "Running Danger"
             swift run danger-swift ci
+
     - cache-push@2.7.1:
         is_always_run: true
     - script@1.2.1:
