For #8163 - Gets url for Nimbus from Info.plist populated by CI

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1094,6 +1094,28 @@ workflows:
             /usr/libexec/PlistBuddy -c "Set LeanplumDevelopmentKey
             $LEANPLUM_KEY_DEVELOPMENT" "Client/Info.plist"
         title: Leanplum Variable Setup
+    - script@1:
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+
+            # fail if any commands fails
+
+            set -e
+
+            # debug log
+
+            set -x
+
+
+            # write your script here
+
+
+            echo "Setting Nimbus variables"
+
+            /usr/libexec/PlistBuddy -c "Set NimbusURL $NIMBUS_URL"
+            "Client/Info.plist"
+        title: Nimbus Variable Setup
     - xcode-archive@2:
         inputs:
         - compile_bitcode: 'no'
@@ -2141,6 +2163,28 @@ workflows:
             /usr/libexec/PlistBuddy -c "Set LeanplumProductionKey $LEANPLUM_KEY_PRODUCTION" "Client/Info.plist"
             /usr/libexec/PlistBuddy -c "Set LeanplumDevelopmentKey $LEANPLUM_KEY_DEVELOPMENT" "Client/Info.plist"
         title: Leanplum Variable Setup
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+
+            # fail if any commands fails
+
+            set -e
+
+            # debug log
+
+            set -x
+
+
+            # write your script here
+
+
+            echo "Setting Nimbus variables"
+
+            /usr/libexec/PlistBuddy -c "Set NimbusURL $NIMBUS_URL"
+            "Client/Info.plist"
+        title: Nimbus Variable Setup
     - script@1:
         inputs:
         - content: |-
