add step to fail standalone builds

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -19,6 +19,7 @@ stages:
 workflows:
   configure_build_fennec:
     before_run:
+    - 0_detect_standalone_build
     - 1_git_clone_and_post_clone
     - 2_certificate_and_profile
     - 3_provisioning_and_npm_installation
@@ -154,6 +155,7 @@ workflows:
         machine_type_id: g2-m1.8core
   build_and_test_1_SmokeTest2:
     before_run:
+    - 0_detect_standalone_build
     - 1_git_clone_and_post_clone
     - Decision_to_run_UI_Tests
     steps:
@@ -196,6 +198,7 @@ workflows:
         machine_type_id: g2-m1.8core
   build_and_test_2_SmokeTest:
     before_run:
+    - 0_detect_standalone_build
     - 1_git_clone_and_post_clone
     - Decision_to_run_UI_Tests
     steps:
@@ -241,6 +244,7 @@ workflows:
         machine_type_id: g2-m1.8core
   build_and_test_3_SmokeTest3:
     before_run:
+    - 0_detect_standalone_build
     - 1_git_clone_and_post_clone
     - Decision_to_run_UI_Tests
     steps:
@@ -286,6 +290,7 @@ workflows:
         machine_type_id: g2-m1.8core
   build_and_test_4_SmokeTest4:
     before_run:
+    - 0_detect_standalone_build
     - 1_git_clone_and_post_clone
     - Decision_to_run_UI_Tests
     steps:
@@ -354,6 +359,30 @@ workflows:
             App|${BITRISE_APP_URL}
             #mobile-testeng|https://mozilla.slack.com/archives/C02KDDS9QM9
             Mana|https://mana.mozilla.org/wiki/display/MTE/Mobile+Test+Engineering
+  0_detect_standalone_build:
+    steps:
+    - script@1:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -ex
+
+            # Check if $BITRISE_PIPELINE_ID is unset or empty
+            # If so, this is a standalone build and we need to fail it
+            if [ -z "$BITRISE_PIPELINE_ID" ]; then
+                echo "Error: BITRISE_PIPELINE_ID is not set."
+                echo "This means you have triggered a build stage individually, instead of the entire pipeline."
+                echo "The build stage you have triggered is ${BITRISE_STAGE}, but you need to rebuild the entire pipeline`."
+                echo "To trigger a rebuild pipeline in its entirety, select your last failed build for `pipeline_multiple_shards`."
+                echo "Then, click the `Rebuild` button."
+                echo "From the dropdown menu, select `Rebuild entire pipeline`."
+                echo "If no dropdown menu is present, you are looking at a standalone build and need to select the initial Github pipeline triggered by the PR."
+                echo "If you are still having issues, please contact #mobile-testeng on Slack."
+                exit 1  # Exit with a failure status
+            else
+                echo "BITRISE_PIPELINE_ID is set to $BITRISE_PIPELINE_ID"
+            fi
+        title: Detect standalone build
   1_git_clone_and_post_clone:
     steps:
     - activate-ssh-key@4:
@@ -1534,6 +1563,7 @@ workflows:
             sed 's/.*=//;s/'\''/"/g' data.txt > test.json
             cat test.json
             python3 perfTestTransform.py
+
 app:
   envs:
   - opts:
