WIP: Bitrise Test Sharding
new vars for unit test plan

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -3,10 +3,34 @@ default_step_lib_source: 'https://github.com/bitrise-io/bitrise-steplib.git'
 project_type: ios
 pipelines:
   pipeline_build_and_test:
-    stages:
-    - pre_configuration: {}
-    - build_applications: {}
-    - run_tests: {}
+    workflows:
+        determine_apps_affected: {}
+        firefox_configure_build:
+            depends_on:
+            - determine_apps_affected
+        focus_configure_build:
+            depends_on:
+            - determine_apps_affected
+        run_firefox_ui_tests:
+            depends_on:
+            - firefox_configure_build
+            parallel: 5
+        focus_ui_test:
+            depends_on:
+            - focus_configure_build
+        focus_unit_test:
+            depends_on:
+            - focus_configure_build
+        klar_unit_test:
+            depends_on:
+            - focus_configure_build
+  pipeline_test_sharding:
+    workflows:
+        firefox_configure_build: {}
+        run_firefox_ui_tests:
+            depends_on:
+            - firefox_configure_build
+            parallel: 4
 stages:
   pre_configuration:
     workflows:
@@ -17,22 +41,7 @@ stages:
         run_if: '{{getenv "BUILD_FIREFOX_IOS" | eq "true"}}'
     - focus_configure_build:
         run_if: '{{getenv "BUILD_FOCUS_IOS" | eq "true"}}'
-  run_tests:
-    workflows:
-    - build_and_test_1_SmokeTest1:
-        run_if: '{{getenv "BUILD_FIREFOX_IOS" | eq "true"}}'
-    - build_and_test_2_SmokeTest2:
-        run_if: '{{getenv "BUILD_FIREFOX_IOS" | eq "true"}}'
-    - build_and_test_3_SmokeTest3:
-        run_if: '{{getenv "BUILD_FIREFOX_IOS" | eq "true"}}'
-    - build_and_test_4_SmokeTest4:
-        run_if: '{{getenv "BUILD_FIREFOX_IOS" | eq "true"}}'
-    - focus_ui_test:
-        run_if: '{{getenv "BUILD_FOCUS_IOS" | eq "true"}}'
-    - focus_unit_test:
-        run_if: '{{getenv "BUILD_FOCUS_IOS" | eq "true"}}'
-    - klar_unit_test:
-        run_if: '{{getenv "BUILD_FOCUS_IOS" | eq "true"}}'
+
 workflows:
   firefox_accessibility_test:
     before_run:
@@ -133,61 +142,58 @@ workflows:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - restore-spm-cache@2.1.1:
         is_always_run: true
-    - script@1.2.1:
-        title: Build for Testing
+    - xcode-build-for-test@3:
         inputs:
-        - content: |
+        - scheme: Fennec
+        - configuration: Fennec_Testing
+        - project_path: /Users/vagrant/git/firefox-ios/Client.xcodeproj
+        - xcodebuild_options: '"COMPILER_INDEX_STORE_ENABLE=NO" "CODE_SIGN_IDENTITY=" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGNING_ALLOWED=NO"'
+        - destination: platform=iOS Simulator,name=iPhone 16,OS=18.2
+    - script@1.2.1:
+        title: Override xctestrun file to UnitTests
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
             set -euxo pipefail
-            echo "-- build-for-testing --"
-            mkdir DerivedData
 
-            xcodebuild -resolvePackageDependencies -onlyUsePackageVersionsFromResolvedFile
-            xcodebuild "-project" "/Users/vagrant/git/firefox-ios/Client.xcodeproj" "-scheme" "Fennec" -configuration "Fennec_Testing" "CODE_SIGNING_ALLOWED=NO" -sdk "iphonesimulator" "-destination" "platform=iOS Simulator,name=iPhone 16,OS=18.2" "COMPILER_INDEX_STORE_ENABLE=NO" "build-for-testing" "CODE_SIGN_IDENTITY=" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGNING_ALLOWED=NO" -derivedDataPath "/Users/vagrant/git/DerivedData" | xcpretty | tee xcodebuild_fennec.log
+            # Point to the Unit tests plan instead of Accessibility
+            UNIT_TESTS_XCTESTRUN="$BITRISE_TEST_BUNDLE_PATH/Fennec_UnitTest_iphonesimulator18.2-arm64.xctestrun"
+            SMOKE_UI_XCTESTRUN="$BITRISE_TEST_BUNDLE_PATH/Fennec_Smoketest1_iphonesimulator18.2-arm64.xctestrun"
 
-            ls /Users/vagrant/git/DerivedData/Build/Products
-            ls /Users/vagrant/git/DerivedData
+            if [ ! -f "$UNIT_TESTS_XCTESTRUN" ]; then
+              echo "ERROR: .xctestrun file not found: $UNIT_TESTS_XCTESTRUN"
+              exit 1
+            fi
+
+            echo "Found UnitTest .xctestrun: $UNIT_TESTS_XCTESTRUN"
+            envman add --key BITRISE_XCTESTRUN_UNIT_TEST_FILE_PATH --value "$UNIT_TESTS_XCTESTRUN"
+            envman add --key BITRISE_XCTESTRUN_SMOKE_TEST_FILE_PATH --value "$SMOKE_UI_XCTESTRUN"
+
     - xcode-test-without-building@0.4.0:
-        run_if: '{{getenv "RUN_UI_TESTS" | eq "Run_UI_Tests"}}'
-        timeout: 1200
+    #    run_if: '{{getenv "RUN_UI_TESTS" | eq "Run_UI_Tests"}}'
+    #    timeout: 1200
         inputs:
         - destination: platform=iOS Simulator,name=iPhone 16,OS=18.2
         - xcodebuild_options: '"COMPILER_INDEX_STORE_ENABLE=NO" "CODE_SIGN_IDENTITY=" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGNING_ALLOWED=NO"'
-        - xctestrun: "/Users/vagrant/git/DerivedData/Build/Products/Fennec_UnitTest_iphonesimulator18.2-arm64.xctestrun"
+        - xctestrun: $BITRISE_TEST_BUNDLE_PATH/Fennec_UnitTest_iphonesimulator18.2-arm64.xctestrun
         - maximum_test_repetitions: 2
+    - xcode-test-shard-calculation@0:
+        inputs:
+        - product_path: $BITRISE_XCTESTRUN_SMOKE_TEST_FILE_PATH
+        - shard_count: 4
+        - destination: $BITRISE_DESTINATION
     - save-spm-cache@1.3.1:
         is_always_run: true
-    - script@1.2.1:
-        run_if: '{{getenv "RUN_UI_TESTS" | eq "Run_UI_Tests"}}'
-        title: Compress Derived Data
-        is_always_run: true
-        inputs:
-        - content: |
-            set -euxo pipefail
-            ls /Users/vagrant/git/DerivedData
-            ls /Users/vagrant/git/DerivedData/Build/Products
-
-            echo "-- compress --"
-            # Add Fennec-iphonesimulator folder
-            # Add All .xctestrun files
-            # Add firefox-ios-test files and test plans
-
-            exec zip -0 -qr "${BITRISE_SOURCE_DIR}/DerivedData.zip" \
-            "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/" \
-            "$BITRISE_SOURCE_DIR/DerivedData/Build/Products/Fennec-iphonesimulator/" \
-            "$BITRISE_SOURCE_DIR/firefox-ios/Client.xcodeproj" \
-            "$BITRISE_SOURCE_DIR/firefox-ios/firefox-ios-tests/" \
-            "$BITRISE_SOURCE_DIR/firefox-ios/Client/" \
-            "$BITRISE_SOURCE_DIR/xcodebuild.log"
     - deploy-to-bitrise-io@2.10.0:
-        run_if: '{{getenv "RUN_UI_TESTS" | eq "Run_UI_Tests" | and (getenv "BITRISE_XCRESULT_PATH" | ne "")}}'
+        #run_if: '{{getenv "RUN_UI_TESTS" | eq "Run_UI_Tests" | and (getenv "BITRISE_XCRESULT_PATH" | ne "")}}'
         inputs:
-        - deploy_path: "${BITRISE_SOURCE_DIR}/DerivedData.zip"
         - pipeline_intermediate_files: |-
-            $BITRISE_XCRESULT_PATH:BITRISE_XCRESULT_PATH
-            ${BITRISE_SOURCE_DIR}/DerivedData.zip:DERIVED_DATA_DIR
+            BITRISE_TEST_SHARDS_PATH
+            BITRISE_TEST_BUNDLE_PATH
+            BITRISE_XCTESTRUN_SMOKE_TEST_FILE_PATH
         is_always_run: true
     - script@1.1.1:
-        run_if: '{{getenv "RUN_UI_TESTS" | eq "Run_UI_Tests"}}'
+        #run_if: '{{getenv "RUN_UI_TESTS" | eq "Run_UI_Tests"}}'
         title: Run Danger 2
         timeout: 360
         inputs:
@@ -249,56 +255,23 @@ workflows:
         - text: Build status using latest Rust-Component
         - webhook_url: $WEBHOOK_SLACK_TOKEN_2
 
-  build_and_test_1_SmokeTest1:
-    envs:
-    - opts:
-        is_expand: false
-      SHARD: '1'
-    after_run:
-    - _build_and_test
-
-  build_and_test_2_SmokeTest2:
-    envs:
-    - opts:
-        is_expand: false
-      SHARD: '2'
-    after_run:
-    - _build_and_test
-
-  build_and_test_3_SmokeTest3:
-    envs:
-    - opts:
-        is_expand: false
-      SHARD: '3'
-    after_run:
-    - _build_and_test
-
-  build_and_test_4_SmokeTest4:
-    envs:
-    - opts:
-        is_expand: false
-      SHARD: '4'
-    after_run:
-    - _build_and_test
-
-  _build_and_test:
+  run_firefox_ui_tests:
     before_run:
-    - 0_detect_standalone_build
     - 1_git_clone_and_post_clone
-    - decision_to_run_UI_Tests
-    - firefox_pull_and_unzip_dependencies
     steps:
-    - xcode-test-without-building@0.4.0:
-        run_if: '{{getenv "RUN_UI_TESTS" | eq "Run_UI_Tests"}}'
+    - pull-intermediate-files@1: {}
+    - xcode-test-without-building@0.4.2:
         timeout: 1200
         inputs:
+        - only_testing: $BITRISE_TEST_SHARDS_PATH/$BITRISE_IO_PARALLEL_INDEX
         - destination: platform=iOS Simulator,name=iPhone 16,OS=18.2
-        - xcodebuild_options: '"-derivedDataPath" "/Users/vagrant/git/DerivedData" "COMPILER_INDEX_STORE_ENABLE=NO" "CODE_SIGN_IDENTITY=" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGNING_ALLOWED=NO"'
-        - xctestrun: "Users/vagrant/git/DerivedData/Build/Products/Fennec_Smoketest${SHARD}_iphonesimulator18.2-arm64.xctestrun"
+        - xcodebuild_options: '"COMPILER_INDEX_STORE_ENABLE=NO" "CODE_SIGN_IDENTITY=" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGNING_ALLOWED=NO"'
+        - xctestrun: $BITRISE_TEST_BUNDLE_PATH/Fennec_Smoketest1_iphonesimulator18.2-arm64.xctestrun
     - deploy-to-bitrise-io@2.10.0:
         run_if: '{{getenv "RUN_UI_TESTS" | eq "Run_UI_Tests"}}'
         inputs:
-        - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_${SHARD}_XCRESULT_PATH'
+        - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_UITESTS_XCRESULT_PATH'
+
   determine_apps_affected:
     steps:
     - git-clone@6.2: {}
@@ -2280,17 +2253,26 @@ app:
   - opts:
       is_expand: false
     BITRISE_NIGHTLY_VERSION: '9000'
+  - opts:
+      is_expand: false
+    BITRISE_PROJECT_PATH: './firefox-ios/Client.xcodeproj'
+  - opts:
+      is_expand: false
+    BITRISE_SCHEME: 'Fennec'
+  - opts:
+      is_expand: false
+    BITRISE_DESTINATION: 'platform=iOS Simulator,name=Bitrise iOS default,OS=latest'
 
 
 trigger_map:
 - push_branch: main
-  pipeline: pipeline_build_and_test
+  pipeline: pipeline_test_sharding
 - push_branch: epic-branch/*
   pipeline: pipeline_build_and_test
 - push_branch: release/*
   pipeline: pipeline_build_and_test
 - pull_request_target_branch: main
-  pipeline: pipeline_build_and_test
+  pipeline: pipeline_test_sharding
 - pull_request_target_branch: epic-branch/*
   pipeline: pipeline_build_and_test
 - pull_request_target_branch: release/v*
