Updated BR to fix issues with XCode 13 upload (#9261)

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -591,47 +591,32 @@ workflows:
         stack: osx-xcode-13.0.x
         machine_type_id: g2.4core
 
-  xcode12-release-and-beta-nocache:
+  xcode13-release-and-beta-nocache:
     steps:
-    - activate-ssh-key@4.0:
+    - activate-ssh-key@4.1:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone@4.0: {}
+    - git-clone@6.1: {}
     - certificate-and-profile-installer@1.10: {}
     - script@1:
         inputs:
-        - content: >-
+        - content: |-
             #!/usr/bin/env bash
-
             # fail if any commands fails
-
             set -e
-
             # debug log
-
             set -x
 
-
-            echo
-            'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64=arm64
-            arm64e armv7 armv7s armv6 armv8' > /tmp/tmp.xcconfig
-
-            echo 'EXCLUDED_ARCHS=$(inherited)
-            $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT))'
-            >> /tmp/tmp.xcconfig
-
+            echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64=arm64 arm64e armv7 armv7s armv6 armv8' > /tmp/tmp.xcconfig
+            echo 'EXCLUDED_ARCHS=$(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT))' >> /tmp/tmp.xcconfig
             echo 'IPHONEOS_DEPLOYMENT_TARGET=11.4' >> /tmp/tmp.xcconfig
-
             echo 'SWIFT_TREAT_WARNINGS_AS_ERRORS=NO' >> /tmp/tmp.xcconfig
-
             echo 'GCC_TREAT_WARNINGS_AS_ERRORS=NO' >> /tmp/tmp.xcconfig
-
             export XCODE_XCCONFIG_FILE=/tmp/tmp.xcconfig
-
             envman add --key XCODE_XCCONFIG_FILE --value /tmp/tmp.xcconfig
         title: Workaround carthage lipo bug
     - carthage@3.2:
         inputs:
-        - carthage_options: ' --platform ios --cache-builds'
+        - carthage_options: " --platform ios --cache-builds"
     - script@1:
         inputs:
         - content: |-
@@ -648,12 +633,8 @@ workflows:
     - script@1:
         title: Move glean sdk_generator
         inputs:
-        - content: >-
-            #!/usr/bin/env bash
-            # fail if any commands fails
-            set -e
-            # debug log
-            set -x
+        - content: |-
+            #!/usr/bin/env bash # fail if any commands fails set -e # debug log set -x
 
             # Move Glean script to source folder from
             # MozillaAppServices.framework as we don't
@@ -663,24 +644,17 @@ workflows:
             mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
     - script@1:
         inputs:
-        - content: >-
+        - content: |-
             #!/usr/bin/env bash
-
             set -e
-
             set -x
 
-
             cd Client.xcodeproj
-
-            sed -i '' 's/CODE_SIGN_IDENTITY = "iPhone
-            Developer"/CODE_SIGN_IDENTITY = "iPhone Distribution"/'
-            project.pbxproj
-
+            sed -i '' 's/CODE_SIGN_IDENTITY = "iPhone Developer"/CODE_SIGN_IDENTITY = "iPhone Distribution"/' project.pbxproj
             cd -
         title: Set xcodeproj code_sign_identity
     - script@1.1:
-        title: 'NPM, ContentBlockerGen'
+        title: NPM, ContentBlockerGen
         inputs:
         - content: |-
             #!/usr/bin/env bash
@@ -710,38 +684,33 @@ workflows:
         - plist_path: WidgetKit/Info.plist
     - script@1:
         inputs:
-        - content: >-
+        - content: |-
             #!/usr/bin/env bash
-
             # fail if any commands fails
-
             set -e
-
             # debug log
-
             set -x
-
 
             # write your script here
 
-
             echo "Setting Nimbus variables"
-
             /usr/libexec/PlistBuddy -c "Set NimbusURL $NIMBUS_URL" "Client/Info.plist"
         title: Nimbus Variable Setup
-    - xcode-archive@2:
+    - xcode-archive@3.3:
         inputs:
         - compile_bitcode: 'no'
         - upload_bitcode: 'no'
         - team_id: 43AQ936H96
         - export_method: app-store
         - output_tool: xcodebuild
-        - configuration: $BITRISE_SCHEME
-    - deploy-to-bitrise-io@1: {}
-    - deploy-to-itunesconnect-application-loader@0:
+        - configuration: "$BITRISE_SCHEME"
+    - deploy-to-bitrise-io@2.0: {}
+    - deploy-to-itunesconnect-application-loader@1.3:
         inputs:
-        - app_password: $APPLE_ACCOUNT_PW
-        - itunescon_user: $APPLE_ACCOUNT_ID
+        - app_password: "$APPLE_ACCOUNT_PW"
+        - password: "$APPLE_ACCOUNT_PW"
+        - connection: 'off'
+        - itunescon_user: "$APPLE_ACCOUNT_ID"
     - script@1:
         inputs:
         - content: |-
@@ -751,10 +720,10 @@ workflows:
             # sleep 9999
         is_always_run: true
         title: debug-sleep
-    - slack@3.1:
+    - slack@3.2:
         inputs:
-        - webhook_url: $WEBHOOK_SLACK_TOKEN
-    - xcode-archive@2:
+        - webhook_url: "$WEBHOOK_SLACK_TOKEN"
+    - xcode-archive@3.3:
         inputs:
         - compile_bitcode: 'no'
         - upload_bitcode: 'no'
@@ -764,22 +733,21 @@ workflows:
         - scheme: FirefoxBeta
         - configuration: FirefoxBeta
         title: 'FirefoxBeta: Xcode Archive & Export for iOS'
-    - deploy-to-itunesconnect-application-loader@0:
+    - deploy-to-itunesconnect-application-loader@1.3:
         inputs:
-        - app_password: $APPLE_ACCOUNT_PW
-        - itunescon_user: $APPLE_ACCOUNT_ID
+        - app_password: "$APPLE_ACCOUNT_PW"
+        - connection: 'off'
+        - itunescon_user: "$APPLE_ACCOUNT_ID"
         title: 'FirefoxBeta: Deploy to iTunes Connect'
     envs:
     - opts:
         is_expand: false
       BITRISE_SCHEME: Firefox
-    description: >-
-      This step is to build, archive and upload Firefox Release and Beta
+    description: This step is to build, archive and upload Firefox Release and Beta
     meta:
       bitrise.io:
         stack: osx-xcode-13.0.x
-        machine_type_id: g2.4core
-
+        machine_type_id: g2.8core
 app:
   envs:
   - opts:
@@ -791,7 +759,7 @@ app:
 trigger_map:
 - push_branch: main
   workflow: RunUnitTests
-- push_branch: v38.0
-  workflow: xcode12-release-and-beta-nocache
+- push_branch: v39.0
+  workflow: xcode13-release-and-beta-nocache
 - pull_request_target_branch: main
   workflow: RunUnitTests
