change danger after unit tests

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -125,17 +125,6 @@ workflows:
             "$BITRISE_SOURCE_DIR/Tests/UnitTest.xctestplan" \
             "$BITRISE_SOURCE_DIR/Client/" \
             "$BITRISE_SOURCE_DIR/Tests/XCUITests"
-    - script@1.1:
-        title: Run Danger
-        is_always_run: true
-        inputs:
-        - content: |
-            #!/usr/bin/env bash
-            # Fail if any command fails
-            set -e
-            echo "Run danger"
-            swift run danger-swift ci
-
     - deploy-to-bitrise-io@2:
         inputs:
         - deploy_path: "${BITRISE_SOURCE_DIR}/DerivedData.zip"
@@ -373,7 +362,19 @@ workflows:
         inputs:
         - search_pattern: "$BITRISE_SOURCE_DIR/xcodebuild.xcresult"
         - test_name: Unit Test
-    - deploy-to-bitrise-io@2.0: {}
+    - deploy-to-bitrise-io@2.0:
+        inputs:
+        - deploy_path: "$BITRISE_SOURCE_DIR/xcodebuild.xcresult"
+    - script@1.1:
+        title: Run Danger
+        is_always_run: true
+        inputs:
+        - content: |
+            #!/usr/bin/env bash
+            # Fail if any command fails
+            set -e
+            echo "Run danger"
+            swift run danger-swift ci
     meta:
       bitrise.io:
         stack: osx-xcode-14.1.x
