- Updated bitrise.yml to fix failing test case due to glean sdk_generator - Before pushing cache to BR we move glean script back to MozillaAppServices framework so it is available for next time a test run takes place

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -881,6 +881,21 @@ workflows:
         - scheme: Fennec
         - simulator_device: iPhone 8
     - deploy-to-bitrise-io@1.9: {}
+    - script@1:
+        title: Move glean sdk_generator back to MozillaAppServices
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script back to
+            # MozillaAppServices.framework
+            # before pushing BR cache
+
+            mv sdk_generator.sh Carthage/Build/iOS/MozillaAppServices.framework/
     - cache-push@2.4: {}
     - slack@3.1:
         inputs:
@@ -1042,6 +1057,21 @@ workflows:
         - scheme: Fennec
         - simulator_device: iPhone 8
     - deploy-to-bitrise-io@1.9: {}
+    - script@1:
+        title: Move glean sdk_generator back to MozillaAppServices
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script back to
+            # MozillaAppServices.framework
+            # before pushing BR cache
+
+            mv sdk_generator.sh Carthage/Build/iOS/MozillaAppServices.framework/
     - cache-push@2.4: {}
     - slack@3.1:
         inputs:
@@ -3083,6 +3113,21 @@ workflows:
         - scheme: Fennec
         - simulator_device: iPhone 8
     - deploy-to-bitrise-io@1.9: {}
+    - script@1:
+        title: Move glean sdk_generator back to MozillaAppServices
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script back to
+            # MozillaAppServices.framework
+            # before pushing BR cache
+
+            mv sdk_generator.sh Carthage/Build/iOS/MozillaAppServices.framework/
     - cache-push@2.4: {}
     - slack@3.1:
         run_if: '{{getenv "NEW_XCODE_VERSION" | eq "New_Version_Found"}}'
