- cleanup and added script to nocache build as well

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1077,7 +1077,7 @@ workflows:
             envman add --key XCODE_XCCONFIG_FILE --value ''
         title: remove carthage lipo workaround
     - script@1:
-        title: Move sdk_generator
+        title: Move glean sdk_generator
         inputs:
         - content: >-
             #!/usr/bin/env bash
@@ -1493,6 +1493,22 @@ workflows:
     - carthage@3.2:
         inputs:
         - carthage_options: ' --platform ios --cache-builds'
+    - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
     - script@1:
         inputs:
         - content: |-
