[Nobug, Build] Updated bitrise.yml to fix build failure due to missing sdk_generator (#8028)

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -796,6 +796,22 @@ workflows:
             envman add --key XCODE_XCCONFIG_FILE --value ''
         title: Remove carthage lipo workaround
     - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
+    - script@1:
         inputs:
         - content: >-
             #!/usr/bin/env bash
@@ -939,6 +955,22 @@ workflows:
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
         title: Remove carthage lipo workaround
+    - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
     - script@1:
         inputs:
         - content: >2-
@@ -1337,6 +1369,22 @@ workflows:
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
         title: remove carthage lipo workaround
+    - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
     - script@1:
         inputs:
         - content: >-
@@ -1747,6 +1795,22 @@ workflows:
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
     - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
+    - script@1:
         inputs:
         - content: >-
             #!/usr/bin/env bash
@@ -1895,6 +1959,22 @@ workflows:
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
         title: remove carthage lipo workaround
+    - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
     - script@1:
         inputs:
         - content: >-
@@ -2117,6 +2197,22 @@ workflows:
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
     - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
+    - script@1:
         inputs:
         - content: >-
             #!/usr/bin/env bash
@@ -2284,6 +2380,22 @@ workflows:
 
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
+    - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
     - script@1:
         inputs:
         - content: >-
@@ -2453,6 +2565,22 @@ workflows:
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
     - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
+    - script@1:
         inputs:
         - content: >-
             #!/usr/bin/env bash
@@ -2604,6 +2732,22 @@ workflows:
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
         title: remove carthage lipo workaround
+    - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
     - script@1:
         inputs:
         - content: >-
@@ -2833,6 +2977,22 @@ workflows:
             rm /tmp/tmp.xcconfig
             envman add --key XCODE_XCCONFIG_FILE --value ''
         title: Remove carthage lipo workaround
+    - script@1:
+        title: Move glean sdk_generator
+        inputs:
+        - content: >-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            # Move Glean script to source folder from
+            # MozillaAppServices.framework as we don't
+            # want to ship our app with Glean shell
+            # script inside A~S framework
+
+            mv Carthage/Build/iOS/MozillaAppServices.framework/sdk_generator.sh ./
     - script@1:
         run_if: '{{getenv "NEW_XCODE_VERSION" | eq "New_Version_Found"}}'
         inputs:
